# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: "ubuntu-20.04"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker hub'
        repository: 'torpu/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: 'Terraforming on Azure ......'
  dependsOn: Build
  jobs: 
  - job: Provision
    displayName: 'Provisioning Container Instance'
    pool:
      vmImage: "ubuntu-20.04"
    variables: 
    - group: TerraformEnvVars
    steps:
    -script: |
       set -e 

       terraform init -input=false
       terraform apply -input=falst -auto-approve
       name:'RunTerraform'
       displayName:'Run Terraform'
      
      env:
              
         ARM_CLIENT_ID:  $(ARM_CLIENT_ID)
         ARM_CLIENT_SECRET:  (ARM_CLIENT_SECRET)
         ARM_TENANT_ID:  $(ARM_TENANT_ID)
         ARM_SUBSCRIPTION_ID:  $(ARM_SUBSCRIPTION_ID)

